import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { NextUIProvider } from "@nextui-org/react";
import React from "react";
import NavComponent from "./_components/navbar";
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NextUIProvider>
          <NavComponent key={"Navigation Section"} />
          {children}
        </NextUIProvider>
      </body>
    </html>
  );
}
