import type { Metadata } from "next";
import * as Sentry from "@sentry/react";
// import setupLogRocketReact  from 'logrocket-react';

Sentry.init({
  dsn: "https://7e85b395ff31ce19ec3e91f06fb9de76@o4508135432716288.ingest.us.sentry.io/4508135434223616",
  integrations: [
    Sentry.browserTracingIntegration(),
    Sentry.replayIntegration(),
  ],
  // Tracing
  tracesSampleRate: 1.0, //  Capture 100% of the transactions
  // Set 'tracePropagationTargets' to control for which URLs distributed tracing should be enabled
  tracePropagationTargets: ["localhost", /^https:\/\/yourserver\.io\/api/],
  // Session Replay
  replaysSessionSampleRate: 0.1, // This sets the sample rate at 10%. You may want to change it to 100% while in development and then sample at a lower rate in production.
  replaysOnErrorSampleRate: 1.0, // If you're not already sampling the entire session, change the sample rate to 100% when sampling sessions where errors occur.
});
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { NextUIProvider } from "@nextui-org/react";
import React from "react";
import NavComponent from "./_components/navbar";
import LogRocketProvider from "./log-rocket";
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NextUIProvider>
          <LogRocketProvider>
            <NavComponent key={"Navigation Section"} />
            {children}
          </LogRocketProvider>
        </NextUIProvider>
      </body>
    </html>
  );
}